sudo: required
dist: trusty
#group: edge
language: python
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"
before_install:
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce

install:
  # ref: https://github.com/metacloud/molecule/issues/783
  - pip install ansible
  - pip install molecule==1.25.0
  # - pip install required driver (e.g. docker, python-vagrant, shade)
  - pip install docker
  - ansible-galaxy install -r requirements.yml
script:
  - molecule create
  - molecule converge
  - molecule syntax
  - molecule idempotence

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
