---
# file roles/burp_server/tasks/cron.yml

### CRON CONFIGURATION ###
# Adding > /dev/null to commands to supress stdout normal emails to root.
# it will send only emails to root if there is some stderr

- name: ensure /etc/cron.d exists
  file:
    path: '/etc/cron.d'
    state: directory

- name: cronenv prepare SHELL env var to run tasks
  cronvar:
    name: SHELL
    value: /bin/bash
    cron_file: 'burp_reports'

- name: cronenv prepare LANG env var to run tasks
  cronvar:
    name: LANG
    value: en_US.UTF-8
    cron_file: 'burp_reports'

- name: cron task for email outdated
  cron: name='burp-server-reports outdated report'
        job='/usr/local/bin/burp-reports -c {{ burp_report_conf }} --report email_outdated'
        user='{{ burp_conf_user }}'
        cron_file='burp_reports'
        special_time='{{ report_outdated_special_time }}'
        state=present

- name: cron task for report inventory
  cron: name='burp-server-reports inventory report'
        job='/usr/local/bin/burp-reports -c {{ burp_report_conf }} --report inventory -i {{ burp_report_inventory_input }} -o {{ burp_report_inventory_output }}'
        user='{{ burp_conf_user }}'
        cron_file='burp_reports'
        special_time='{{ report_inventory_special_time }}'
        state=present
  when: burp_report_inventory_input and burp_report_inventory_output and burp_report_inventory_cron_enabled

- name: disable cron task for report inventory
  cron: name='burp-server-reports inventory report'
        job='/usr/local/bin/burp-reports -c {{ burp_report_conf }} --report inventory -i {{ burp_report_inventory_input }} -o {{ burp_report_inventory_output }}'
        user='{{ burp_conf_user }}'
        cron_file='burp_reports'
        special_time='{{ report_inventory_special_time }}'
        state=absent
  when: not burp_report_inventory_cron_enabled

- block:
    - name: cron task for reports commands
      cron:
        name: "{{ item.name }}"
        job: "{{ item.job }}"
        user: "{{ burp_conf_user }}"
        cron_file: 'burp_reports'
        day: "{{ item.day | default('*') }}"
        minute: "{{ item.minute | default('*/10') }}"
        hour: "{{ item.hour | default('*') }}"
        month: "{{ item.month | default('*') }}"
        weekday: "{{ item.weekday | default('*') }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ burp_reports_cron_jobs }}"
  when: burp_reports_cron_jobs | bool

# Removed for compatibility with xenial
# Enable cron to start up on boot
# - name: ensure cron is enabled
#   service:
#     name: cron
#     enabled: yes

# Start cron server service
# - name: ensure cron is started
#   service:
#     name: cron
#     state: started
