---
# file roles/burp_server/tasks/cron.yml

### CRON CONFIGURATION ###
# Adding > /dev/null to commands to supress stdout normal emails to root.
# it will send only emails to root if there is some stderr

- name: ensure /etc/cron.d exists
  file:
    path: '/etc/cron.d'
    state: directory

- cron: name='burp-server-reports outdated report'
        job='burp-reports -c {{ burp_report_conf }} --report email_outdated'
        user='{{ burp_conf_user }}'
        cron_file='burp_reports'
        special_time='{{ report_outdated_special_time }}'
        state=present

- cron: name='burp-server-reports inventory report'
        job='burp-reports -c {{ burp_report_conf }} --report inventory -i {{ burp_report_inventory_input }} -o {{ burp_report_inventory_output }}'
        user='{{ burp_conf_user }}'
        cron_file='burp_reports'
        special_time='{{ report_inventory_special_time }}'
        state=present
  when: burp_report_inventory_input and burp_report_inventory_output

# Removed for compatibility with xenial
# Enable cron to start up on boot
#- name: ensure cron is enabled
#  service:
#    name: cron
#    enabled: yes

# Start cron server service
#- name: ensure cron is started
#  service:
#    name: cron
#    state: started
