---
# file roles/burp_reports/tasks/scripts.yml

# Install burp_reports

- name: upgrade pip 
  pip:
    name: "pip"
    executable: "{{ pip_exec }}"
    state: present
    version: "9.0.1"

- name: install role pip packages
  pip:
    name: "{{ item.name }}"
    executable: "{{ pip_exec }}"
    state: present
    version: "{{ item.version }}"
  with_items: "{{ burp_reports_pip_packages }}"

- name: "Ensure {{ burp_etc }} exists"
  file:
    path: "{{ burp_etc }}"
    state: directory

# Copy burp report configuration file
- name: set burp-reports.conf file
  template:
    src: 'burp-reports.conf.j2'
    dest: '{{ burp_report_conf }}'
    owner: '{{ burp_conf_user }}'
    group: '{{ burp_conf_group }}'
    mode: 0644