---
# file: roles/burp_reports/tasks/main.yml

- include: multi_os.yml
  tags:
    - config_burp_reports_cron
    - test_burp_reports

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: install burp_reports system dependencies
  package: name={{ burp_reports_sys_packages| join(',') }} state=present

- include: install.yml

- include: cron.yml
  tags:
    - config_burp_reports_cron

- include: reports_tests.yml
  when: burp_report_test
  tags:
    - test_burp_reports