---
# file: roles/burp_reports/tasks/main.yml

- include_tasks: multi_os.yml
  tags:
    - config_burp_reports_cron
    - test_burp_reports

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: install burp_reports system dependencies
  package: name={{ burp_reports_sys_packages| join(',') }} state=present

- include_tasks: install.yml

- include_tasks: nsca.yml

- include_tasks: cron.yml
  tags:
    - config_burp_reports_cron

- include_tasks: reports_tests.yml
  when: burp_report_test
  tags:
    - test_burp_reports