---

- name: redhat | install EPEL release package for RHEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: redhat | install EPEL release package for Centos
  yum:
    name: "epel-release"
    state: present
  when: ansible_distribution == 'CentOS'

- name: set var ius_distribution_abbrev
  set_fact:
    ius_distribution_abbrev: "{{ (ansible_distribution == 'CentOS') | ternary('centos', 'rhel') }}"

# Must be state: present due to deficiency in ansible. See:
# https://github.com/ansible/ansible-modules-core/issues/948
- name: redhat | install IUS release package
  yum:
    name: "https://{{ ius_distribution_abbrev }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution != "Fedora"

- name: redhat | set pip3 packages for redhat and centos
  set_fact:
    burp_reports_sys_packages:
        - python36
        - python36-devel
        - python36-setuptools
        - python36-pip
        - redhat-rpm-config
        - openssl-devel
        - libffi-devel
        - gcc
        - cronie
  when: ansible_distribution != "Fedora"
