---
# Tests tasks for scripts

- name: Test burp-reports
  command: burp-reports -c {{ burp_report_conf }} --report outdated
  changed_when: false
  become: false
  tags:
    - skip_ansible_lint

- name: Test inventory
  command: burp-reports -c {{ burp_report_conf }} --report inventory -i {{ burp_report_inventory_input }} -o test_inventory.csv
  when: burp_report_inventory_input and burp_report_inventory_output
  changed_when: false
  become: false
  environment: 
      http_proxy: ""
      https_proxy: ""
  tags:
    - skip_ansible_lint
