---
# Tests tasks for scripts

- name: Test burp-reports
  command: burp-reports -c {{ burp_report_conf }} --report outdated

- name: Test inventory
  shell: 'burp-reports -c {{ burp_report_conf }} --report inventory -i {{ burp_report_inventory_input }} -o {{ burp_report_inventory_output }}'
  when: burp_report_inventory_input and burp_report_inventory_output